# Generated by Django 4.1.5 on 2023-02-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='work_order',
            name='wo_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Work Order Number'),
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(verbose_name='Bill Number')),
                ('bill_date', models.DateField(verbose_name='Bill Date')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('created_by', models.IntegerField(verbose_name='Created By')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workorders.work_order')),
            ],
        ),
    ]
