# Generated by Django 4.1.5 on 2023-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_work_order_status_alter_work_order_wo_number_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(max_length=10, verbose_name='Bill Number'),
        ),
    ]
