# Generated by Django 4.1.5 on 2023-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_alter_bill_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='basic_amount',
            field=models.FloatField(default=0, verbose_name='Basic Amount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax',
            field=models.FloatField(default=1.0, verbose_name='Tax( 0.10% - 30/% )'),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_by',
            field=models.IntegerField(default=1, verbose_name='Created By'),
        ),
    ]
