# Generated by Django 4.1.4 on 2023-02-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_remove_bill_amount_bill_basic_amount_bill_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(max_length=10, unique=True, verbose_name='Bill Number'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.FloatField(default=0.1, verbose_name='Tax( 0.10% - 30/% )'),
        ),
        migrations.CreateModel(
            name='rejection_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('rejected_by', models.IntegerField(default=1, verbose_name='Rejected By')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workorders.work_order')),
            ],
        ),
    ]
